### ISSUE TITLE
V2: Error 401 on apps in remote

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#107]
Remote access seems to have trouble:
![Peek 2020-11-19 12-10](https://user-images.githubusercontent.com/484033/99658839-5074f000-2a60-11eb-945c-5e7c3bebca68.gif)

Some menu entries are missing, the apps page shows "401" and it's impossible to log out.
Is it a conflict between the Cloud dashboard Auth method and the gateway auth method? Both uses tokens.

**Comment by mojtaba-esk** [comment]
I cannot even login to test it and have no idea how can fix it.

![image](https://user-images.githubusercontent.com/13765532/99672475-bfa80f80-2a73-11eb-8b96-a30e88ddcdd7.png)

@j-forster can you please shed some lights here?

**Comment by j-forster** [comment]
- make sure you are on the right device
- maybe you need to logout and login again at the cloud if the device was just created
- is it shown as "connected" at the cloud dashboard?
- check that the URL now doesn't end with /admin or something
- now check again if you are on the right device
- is the edge sync enabled?
- any errors on the edge log? Look for `[TUNL ]` and `[UP   ]`
- Are you working on the dashboard right now? Make sure it's compiled as "production" to work with the tunnel

**Comment by mojtaba-esk** [comment]
I did all and it still does not work. I will test with a production wazigate to see if it works.

**Comment by mojtaba-esk** [comment]
I found out what is the issue with **logout**
When user logs into the wazigate dashboard directly (being in the same network), wazigate creates a jwt token and stores it in a coockie on the browser and on logout, it deletes the cookie storing the token and the user is no longer able to use the dashboard.

However, the login procedure does not happen when accessing through **remote**, it goes internally through the _white list_ which sets a various set of cookies (inc. token) on the browser.
Therefore, we need to know what we expect the logout here to do.

Should it logout from the entire Waziup cloud dashboard? or just do something else?

My suggestion is since there is no login page when accessing from remote, we just hide the logout too. it should appear when accessing locally.

**Comment by j-forster** [comment]
> My suggestion is since there is no login page when accessing from remote, we just hide the logout too. it should appear when accessing locally.

I agree with that.

**Comment by j-forster** [comment]
The issue was resolved by https://github.com/Waziup/wazigate-edge/commit/cdb387feb3ad0cc0bcdb0ff7ea0186f6a0adb9a2.

**Comment by cdupont** [comment]
I still have the error 401 on apps in remote... I pulled everything, compiled the edge, and restarted

**Comment by cdupont** [comment]
Working now, suggest closing

**Comment by mojtaba-esk** [comment]
I am not done with that yet. The SD card on my gateway got corrupted last night, so I installed and built everything again. There are small fixes I will do and build and then push the new image to the docker hub.

**Comment by cdupont** [comment]
OK I misunderstood, I let you close when ready.
